/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author: Ian Cunningham
 * @student Number: x13114425
 * @File: DreamTeamGUI.java
 */
public class DreamTeamGUI extends javax.swing.JFrame {
    private ArrayList <DreamTeam> dtList;
    private String name, goalkeeper, leftBack, rightBack, centerBack, centerBack2;
    private String leftMid, rightMid, centerMid, centerMid2, striker, striker2;
    private int count;
    

    /**
     * Creates new form DreamTeamGUI
     */
    public DreamTeamGUI() {
        initComponents();
       dtList = new ArrayList <>();
       name = new String();
       goalkeeper = new String();
       leftBack = new String();
       rightBack = new String();
       centerBack = new String();
       centerBack2 = new String();
       leftMid = new String();
       rightMid = new String();
       centerMid = new String();
       centerMid2 = new String();
       striker = new String();
       striker2 = new String();
       count = 0;
       LoadFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        goalkeeperTF = new javax.swing.JTextField();
        leftBackTF = new javax.swing.JTextField();
        rightBackTF = new javax.swing.JTextField();
        centerBackTF = new javax.swing.JTextField();
        centerBack2TF = new javax.swing.JTextField();
        leftMidTF = new javax.swing.JTextField();
        rightMidTF = new javax.swing.JTextField();
        centerMidTF = new javax.swing.JTextField();
        centerMid2TF = new javax.swing.JTextField();
        strikerTF = new javax.swing.JTextField();
        striker2TF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        pitchLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        goalkeeperTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(goalkeeperTF);
        goalkeeperTF.setBounds(190, 500, 69, 22);

        leftBackTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(leftBackTF);
        leftBackTF.setBounds(70, 440, 69, 22);

        rightBackTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(rightBackTF);
        rightBackTF.setBounds(310, 440, 69, 22);

        centerBackTF.setMinimumSize(new java.awt.Dimension(69, 22));
        jPanel1.add(centerBackTF);
        centerBackTF.setBounds(140, 470, 69, 22);

        centerBack2TF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(centerBack2TF);
        centerBack2TF.setBounds(240, 470, 69, 22);

        leftMidTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(leftMidTF);
        leftMidTF.setBounds(100, 340, 69, 22);

        rightMidTF.setPreferredSize(new java.awt.Dimension(69, 22));
        rightMidTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightMidTFActionPerformed(evt);
            }
        });
        jPanel1.add(rightMidTF);
        rightMidTF.setBounds(281, 340, 69, 22);

        centerMidTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(centerMidTF);
        centerMidTF.setBounds(140, 380, 69, 22);

        centerMid2TF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(centerMid2TF);
        centerMid2TF.setBounds(230, 380, 69, 22);

        strikerTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(strikerTF);
        strikerTF.setBounds(150, 290, 69, 22);

        striker2TF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(striker2TF);
        striker2TF.setBounds(230, 290, 69, 22);

        nameTF.setPreferredSize(new java.awt.Dimension(69, 22));
        jPanel1.add(nameTF);
        nameTF.setBounds(120, 570, 69, 22);

        titleLbl.setFont(new java.awt.Font("Mangal", 0, 30)); // NOI18N
        titleLbl.setText("Dream Team");
        jPanel1.add(titleLbl);
        titleLbl.setBounds(170, 70, 186, 40);

        nameLbl.setFont(new java.awt.Font("Mangal", 0, 12)); // NOI18N
        nameLbl.setText("Name:");
        jPanel1.add(nameLbl);
        nameLbl.setBounds(80, 570, 35, 22);

        pitchLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Pitch.fw.png"))); // NOI18N
        jPanel1.add(pitchLbl);
        pitchLbl.setBounds(25, 200, 400, 400);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Back Button.png"))); // NOI18N
        backBtn.setBorder(null);
        backBtn.setContentAreaFilled(false);
        backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backHover.fw.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(5, 5, 50, 50);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2.png"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeHover.fw.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(70, 5, 50, 50);

        addBtn.setText("Add Dream Team");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(30, 620, 150, 25);

        displayBtn.setText("Display All");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayBtn);
        displayBtn.setBounds(270, 620, 150, 25);

        searchBtn.setText("Search by Name");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn);
        searchBtn.setBounds(270, 660, 150, 25);

        deleteBtn.setText("Delete Dream Team");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(30, 660, 147, 25);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);
        saveBtn.setBounds(25, 160, 100, 25);

        viewBtn.setText("View Saved");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBtn);
        viewBtn.setBounds(325, 160, 100, 25);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/BackgroundNoText.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rightMidTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightMidTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rightMidTFActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        name = nameTF.getText();
        goalkeeper = goalkeeperTF.getText();
        leftBack = leftBackTF.getText();
        rightBack = rightBackTF.getText();
        centerBack = centerBackTF.getText();
        centerBack2 = centerBack2TF.getText();
        leftMid = leftMidTF.getText();
        rightMid = rightMidTF.getText();
        centerMid = centerMidTF.getText();
        centerMid2 = centerMid2TF.getText();
        striker = strikerTF.getText();
        striker2 = striker2TF.getText();
        
        DreamTeam a = new DreamTeam();
        a.setName(name);
        a.setGoalkeeper(goalkeeper);
        a.setLeftBack(leftBack);
        a.setRightBack(rightBack);
        a.setCenterBack(centerBack);
        a.setCenterBack2(centerBack2);
        a.setLeftMid(leftMid);
        a.setRightMid(rightMid);
        a.setCenterMid(centerMid);
        a.setCenterMid2(centerMid2);
        a.setStriker(striker);
        a.setStriker2(striker2);
        
        //add object to arraylist
        dtList.add(a);
        
        //increment counter
        count++;
        
        JOptionPane.showMessageDialog(null, "Your team was successfully added");
        
        //reset the textfields to blank
        nameTF.setText("");
        goalkeeperTF.setText("");
        leftBackTF.setText("");
        rightBackTF.setText("");
        centerBackTF.setText("");
        centerBack2TF.setText("");
        leftMidTF.setText("");
        rightMidTF.setText("");
        centerMidTF.setText("");
        centerMid2TF.setText("");
        strikerTF.setText("");
        striker2TF.setText("");
   
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < dtList.size();i++){
            JOptionPane.showMessageDialog(null, "Name: "+dtList.get(i).getName()+"\n GK: "+dtList.get(i).getGoalkeeper()+"\n LB: "+dtList.get(i).getLeftBack()+"\n RB: "+dtList.get(i).getRightBack()+"\n CB: "+dtList.get(i).getCenterBack()+"\n CB: "+dtList.get(i).getCenterBack2()+"\n LM: "+dtList.get(i).getLeftMid()+"\n RM: "+dtList.get(i).getRightMid()+"\n CM: "+dtList.get(i).getCenterMid()+"\n CM: "+dtList.get(i).getCenterMid2()+"\n ST: "+dtList.get(i).getStriker()+"\n ST: "+dtList.get(i).getStriker2());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        String searchName = JOptionPane.showInputDialog(null,"Please enter the name of your dream team you wish to search for");
        
        for(DreamTeam x:dtList){
            if(searchName.equalsIgnoreCase(x.getName())){
                JOptionPane.showMessageDialog(null, "Name: "+x.getName()+"\n GK: "+x.getGoalkeeper()+"\n LB: "+x.getLeftBack()+"\n RB: "+x.getLeftBack()+"\n CB: "+x.getCenterBack()+"\n CB: "+x.getCenterBack2()+"\n LM: "+x.getLeftMid()+"\n RM: "+x.getRightMid()+"\n CM: "+x.getCenterMid()+"\n CM: "+x.getCenterMid2()+"\n ST: "+x.getStriker()+"\n ST: "+x.getStriker2());
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        if(nameTF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter the name of your Dream Team to delete");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null,"Sorry, there are no teams to delete at this time");
        }
        else{
            name = nameTF.getText();
            
            for(int i = 0; i < dtList.size();i++){
                if(dtList.get(i).getName().equalsIgnoreCase(name)){
                    dtList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null,"Deleted team "+name);
                    break;
                }
                if(i==count-1){
                    JOptionPane.showMessageDialog(null,"Sorry, that team could not be found");
                }
            }
        }
         //reset the textfields to blank
                    nameTF.setText("");
                    goalkeeperTF.setText("");
                    leftBackTF.setText("");
                    rightBackTF.setText("");
                    centerBackTF.setText("");
                    centerBack2TF.setText("");
                    leftMidTF.setText("");
                    rightMidTF.setText("");
                    centerMidTF.setText("");
                    centerMid2TF.setText("");
                    strikerTF.setText("");
                    striker2TF.setText("");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        WorldCup myHome = new WorldCup();
        myHome.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        Teams myTeams = new Teams();
        myTeams.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    public void LoadFile(){   
        // Declare objects required to read from file
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        //use a try statement
      try{
            //create objects
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            //read arrayList from file
            ArrayList <DreamTeam> xList;
            xList = (ArrayList<DreamTeam>)oStream.readObject();
          
            //close the stream
            oStream.close();
      }
        //catch IOException
        catch(IOException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        //Declare objects required to write object to a file
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
   
        //try statement
        try{
            //create objects
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            //write object    
            oStream.writeObject(dtList);
            
            JOptionPane.showMessageDialog(null,"File written successfully");
            
            //close stream
            oStream.close();
        }
        //catch the IOException
       catch(IOException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // Declare objects required to read from file
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        //use a try statement
      try{
            //create objects
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
           
            //read arrayList from file
            ArrayList <DreamTeam> xList;
            xList = (ArrayList<DreamTeam>)oStream.readObject();
            //loop through the ArrayList
            for(DreamTeam x:xList){
            //Print the contents of each object
            JOptionPane.showMessageDialog(null, "Name: "+x.getName()+"\n GK: "+x.getGoalkeeper()+"\n LB: "+x.getLeftBack()+"\n RB: "+x.getRightBack()+"\n CB: "+x.getCenterBack()+"\n CB: "+x.getCenterBack2()+"\n LM: "+x.getLeftMid()+"\n RM: "+x.getRightMid()+"\n CM: "+x.getCenterMid()+"\n CM: "+x.getCenterMid2()+"\n ST: "+x.getStriker()+"\n ST: "+x.getStriker2());
            }
          
            //close the stream
            oStream.close();
      }
        //catch IOException
        catch(IOException | ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_viewBtnActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DreamTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DreamTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DreamTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DreamTeamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DreamTeamGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JTextField centerBack2TF;
    private javax.swing.JTextField centerBackTF;
    private javax.swing.JTextField centerMid2TF;
    private javax.swing.JTextField centerMidTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JTextField goalkeeperTF;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField leftBackTF;
    private javax.swing.JTextField leftMidTF;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel pitchLbl;
    private javax.swing.JTextField rightBackTF;
    private javax.swing.JTextField rightMidTF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField striker2TF;
    private javax.swing.JTextField strikerTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
