/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * GameGUI2.java
 * @author Richie Mangan
 * X13114514
 * This is the game class that will use the questions created in the "QuestionBank" class
 */
public class GameGUI2 extends javax.swing.JFrame {
    //Declaring variables
    String userAns, scoreboard;
    int score, count;

    /**
     * Creates new form Game
     */
    public GameGUI2() {
        initComponents();
        //initializing variables
        userAns = new String();
        scoreboard = new String();
        score = 0;
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        startBtn = new javax.swing.JButton();
        scoreboardBtn = new javax.swing.JButton();
        detailsLbl = new javax.swing.JLabel();
        picLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        leaderLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTa = new javax.swing.JTextArea();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setLayout(null);

        startBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/R2.png"))); // NOI18N
        startBtn.setBorderPainted(false);
        startBtn.setContentAreaFilled(false);
        startBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/R2 hover.png"))); // NOI18N
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });
        backgroundPanel.add(startBtn);
        startBtn.setBounds(230, 468, 220, 70);

        scoreboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/R1.png"))); // NOI18N
        scoreboardBtn.setBorderPainted(false);
        scoreboardBtn.setContentAreaFilled(false);
        scoreboardBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/R1 hover.png"))); // NOI18N
        scoreboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreboardBtnActionPerformed(evt);
            }
        });
        backgroundPanel.add(scoreboardBtn);
        scoreboardBtn.setBounds(310, 610, 140, 70);
        backgroundPanel.add(detailsLbl);
        detailsLbl.setBounds(170, 160, 260, 40);

        picLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/quizLogo.png"))); // NOI18N
        backgroundPanel.add(picLbl);
        picLbl.setBounds(190, 150, 250, 170);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2_2 (2).png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2hover.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        backgroundPanel.add(homeBtn);
        homeBtn.setBounds(0, 0, 60, 60);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Back Button (2).png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backHover.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        backgroundPanel.add(backBtn);
        backBtn.setBounds(390, 0, 60, 60);

        leaderLbl.setFont(new java.awt.Font("Helvetica LT Std", 1, 18)); // NOI18N
        leaderLbl.setForeground(new java.awt.Color(255, 255, 255));
        leaderLbl.setText("Quiz Leaderboard");
        backgroundPanel.add(leaderLbl);
        leaderLbl.setBounds(240, 320, 170, 30);

        detailsTa.setColumns(20);
        detailsTa.setRows(5);
        jScrollPane1.setViewportView(detailsTa);

        backgroundPanel.add(jScrollPane1);
        jScrollPane1.setBounds(190, 346, 250, 110);

        backgroundLbl.setForeground(new java.awt.Color(255, 255, 255));
        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backgroundquiz.jpg"))); // NOI18N
        backgroundPanel.add(backgroundLbl);
        backgroundLbl.setBounds(1, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(468, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        // This code starts the quiz by pulling in question objects from the outpt.data file
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            inFile = new File("output3.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            //arraylist for storing the items from the inFile
            ArrayList<QuestionsAnswers> cList;
            cList = (ArrayList<QuestionsAnswers>) oStream.readObject();
            JOptionPane.showMessageDialog(null, "Welcome! \nA series of questions of varying\n difficulty will follow. \nYour points will be added up at the end. \nGood Luck! ");
            
            //for loop to traverse through each object in the file
            for (QuestionsAnswers c : cList) {
               userAns = JOptionPane.showInputDialog(null, "Question: " + c.getQuestion());
                if (userAns.equalsIgnoreCase(c.getAnswer())) {
                    //output to the user to confirm correct answer and increase score counter
                    JOptionPane.showMessageDialog(null, "Well done! You scored " + c.getMark() + " points ");
                    score = score + c.getMark();
                } 
                else {
                    //outputting correct answer to the user after failed guess
                    JOptionPane.showMessageDialog(null, "Sorry, The correct answer is " + c.getAnswer());
                }
                count++;
            }
            //if statement checking if all questions have been answered to determine end of game
            if (count == cList.size()) {
                scoreboard = JOptionPane.showInputDialog(null, "Thanks for playing. Your score is: " + score + "\nPlease enter your Name below: ");

            }
            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);
        }
        
        //writing a text file for the scoreboard
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        try {
            outFile = new File("Scoreboard.txt");
            fw = new FileWriter(outFile, true);
            bw = new BufferedWriter(fw);

            bw.write(scoreboard+ ". Score: "+ score);
            bw.newLine();
            bw.close();
            JOptionPane.showMessageDialog(null, "Your score has been saved: ");
        } 
        catch (IOException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_startBtnActionPerformed

    private void scoreboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreboardBtnActionPerformed
        // This code reads in info from the scoreboard.txt file by using file I/O with Text
        String name;
        detailsTa.setText("");
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("Scoreboard.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            name = br.readLine();
            while (name != null) {
                detailsTa.append(name + "\n");
                //JOptionPane.showMessageDialog(null, name);
                name = br.readLine();  
            }
            br.close();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_scoreboardBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // Home button code to take user back to first page
        WorldCup myHome = new WorldCup();
        myHome.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // Back button code to go back 1 place at a time
        RulesRegsGUI myRules = new RulesRegsGUI();
        myRules.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GameGUI2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel detailsLbl;
    private javax.swing.JTextArea detailsTa;
    private javax.swing.JButton homeBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leaderLbl;
    private javax.swing.JLabel picLbl;
    private javax.swing.JButton scoreboardBtn;
    private javax.swing.JButton startBtn;
    // End of variables declaration//GEN-END:variables
}
