/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *QuestionBank.java
 * @author Richie Mangan
 * X13114514
 * This class will allow the user to store rules and regs trivia questions, answer and marks depending on the difficulty of the question.
 */
public class QuestionBankGUI extends javax.swing.JFrame {
    //declaring arraylist and variables
    private ArrayList<QuestionsAnswers> qList;
    private String question, answer, keyword;
    private int mark, counter;
    /**
     * Creates new form RefsGuessGUI
     */
    public QuestionBankGUI() {
        initComponents();
        qList = new ArrayList<>();
        question = new String();
        answer = new String();
        keyword = new String();
        mark = 0;
        counter = 0;
        questionTa.setText("You can add rules and regs trivia\n questions here.You can also\n add a keyword for searching the\n questions and a mark depending\n on answer difficulty. \n\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questionTa = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        answerTf = new javax.swing.JTextField();
        markTf = new javax.swing.JTextField();
        questionTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        keywordTf = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        readBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        questionTa.setColumns(20);
        questionTa.setRows(5);
        jScrollPane1.setViewportView(questionTa);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 210, 330);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 2.png"))); // NOI18N
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 2 hover.png"))); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);
        saveBtn.setBounds(310, 336, 140, 70);

        answerTf.setText("Enter Answer Here: ");
        answerTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTfActionPerformed(evt);
            }
        });
        jPanel1.add(answerTf);
        answerTf.setBounds(230, 170, 210, 22);

        markTf.setText("Enter Points Here:");
        jPanel1.add(markTf);
        markTf.setBounds(230, 230, 130, 22);

        questionTf.setText("Enter Question Here:");
        jPanel1.add(questionTf);
        questionTf.setBounds(230, 140, 210, 22);

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 1.png"))); // NOI18N
        addBtn.setBorderPainted(false);
        addBtn.setContentAreaFilled(false);
        addBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 1 hover.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(360, 272, 90, 60);

        displayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 4.png"))); // NOI18N
        displayBtn.setBorderPainted(false);
        displayBtn.setContentAreaFilled(false);
        displayBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 4 hover.png"))); // NOI18N
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(displayBtn);
        displayBtn.setBounds(210, 482, 240, 70);

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 3.png"))); // NOI18N
        searchBtn.setBorderPainted(false);
        searchBtn.setContentAreaFilled(false);
        searchBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 3 hover.png"))); // NOI18N
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel1.add(searchBtn);
        searchBtn.setBounds(260, 409, 190, 70);

        keywordTf.setText("Keyword Here:");
        jPanel1.add(keywordTf);
        keywordTf.setBounds(230, 200, 130, 22);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 5.png"))); // NOI18N
        deleteBtn.setBorderPainted(false);
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 5 hover.png"))); // NOI18N
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(162, 556, 290, 70);

        readBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 6.png"))); // NOI18N
        readBtn.setBorderPainted(false);
        readBtn.setContentAreaFilled(false);
        readBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/button 6 hover.png"))); // NOI18N
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });
        jPanel1.add(readBtn);
        readBtn.setBounds(122, 630, 330, 70);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2_2.png"))); // NOI18N
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2hover.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 60, 60);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Back Button_2.png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backHover.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(390, 0, 60, 60);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backgroundTrivia.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(468, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void answerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTfActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //Taking input from text fields and adding to an object in the array list
        question = questionTf.getText();
        answer = answerTf.getText();
        keyword = keywordTf.getText();
        mark = Integer.parseInt(markTf.getText());
        //creating a new instance of the QuestionsAnswers class called "a"
        QuestionsAnswers a = new QuestionsAnswers();
        //adding the variales to object "a"
        a.setQuestion(question);
        a.setAnswer(answer);
        a.setKeyword(keyword);
        a.setMark(mark);
        //adding "a" object to the array list
        qList.add(a);
        counter++;
        //Displaying "Success" message to the user and clearing the text fields for next input
        questionTa.setText("Success!");
        questionTf.setText("Question");
        answerTf.setText("Answer");
        keywordTf.setText("Keyword");
        markTf.setText("");
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        //traversing the loop and displaying contents of all user inputted data in the array.
        for (int i = 0; i < qList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Question: " + qList.get(i).getQuestion() + "\nAnswer: " + qList.get(i).getAnswer() + "\nKeyword: " + qList.get(i).getKeyword() + "\nPoints: " + qList.get(i).getMark());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        //importing the File I/O classes in order to write objects to a file called output.data
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
           String tester;
        try {
            outFile = new File("output3.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            //writing the object "b" to the file
            oStream.writeObject(qList);
            
             //Telling the user if save has been succesful
            JOptionPane.showMessageDialog(null, "Sucessful! ");
            
            //Closing the stream
            oStream.close();
        } 
        catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // Declaring a "Search" variable to take user search and compare with fields in the arrayList 
        String search = JOptionPane.showInputDialog("Please enter a question: ");
        //Traversing the loop to check for matches with user entry
        for (int i = 0; i < qList.size(); i++) {
            if (search.equalsIgnoreCase(qList.get(i).getKeyword())) {
                //ouputting all contents of matching object to the user
                questionTa.setText("Here's your result: " + "\nQuestion: " + qList.get(i).getQuestion() + "\nAnswer: " + qList.get(i).getAnswer() + "\nPoints: " + qList.get(i).getMark());
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        //Importing File IO classes to read in objects from the saved file
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        questionTa.setText("");
        try {
            inFile = new File("output3.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            ArrayList<QuestionsAnswers> cList;
            cList = (ArrayList<QuestionsAnswers>) oStream.readObject();
            for (QuestionsAnswers c : cList) {
                questionTa.append( "Question: " + c.getQuestion() + "\nAnswer: " + c.getAnswer() + "\nKeyword: " + c.getKeyword() + "\nPoints: " + c.getMark() +"\n\n");
            }
            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_readBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // Home button code to go back to first page
        WorldCup myHome = new WorldCup();
        myHome.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // back button code to go back one place at a time
        RulesRegsGUI myRegs = new RulesRegsGUI();
        myRegs.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // If statement to check if all required fields are correct before allowing delete
        if(questionTf.getText().equals(" ") || answerTf.getText().equals(" ") || markTf.getText().equals(" ") ){
            JOptionPane.showMessageDialog(null, "You must fill all fields before deleting: ");
        }
        else if (qList.isEmpty()){
            //alerting user that no items are in the arraylist
            JOptionPane.showMessageDialog(null, "There are no items to delete: ");
        }
        else{
            question = questionTf.getText();
            answer = answerTf.getText();
            mark = Integer.parseInt(markTf.getText());
            
            for(int i = 0; i < qList.size(); i++){
                if(qList.get(i).getQuestion().equalsIgnoreCase(question) && qList.get(i).getAnswer().equalsIgnoreCase(answer)){
                    qList.remove(i);
                    JOptionPane.showMessageDialog(null, "Deleted the item at index "+i);
                    break;
            }
                if (i == qList.size() -1){
                    //alert for user to inform item could not be found
                    JOptionPane.showMessageDialog(null,"Sorry, the item could not be found: ");
                }
            
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionBankGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new QuestionBankGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField answerTf;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField keywordTf;
    private javax.swing.JTextField markTf;
    private javax.swing.JTextArea questionTa;
    private javax.swing.JTextField questionTf;
    private javax.swing.JButton readBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
