/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

/**
 *
 * @author Richie
 */
public class refGuess extends javax.swing.JFrame {

    /**
     * Creates new form refGuess
     */
    public refGuess() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        guessTf = new javax.swing.JTextField();
        refPic = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        TextArea.setViewportView(jTextArea1);

        getContentPane().add(TextArea);
        TextArea.setBounds(130, 570, 166, 96);

        guessTf.setText("Guess Nationality Here:");
        guessTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessTfActionPerformed(evt);
            }
        });
        getContentPane().add(guessTf);
        guessTf.setBounds(130, 530, 170, 22);

        refPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/webb_1076105a.jpg"))); // NOI18N
        refPic.setText("Referee pic here:");
        getContentPane().add(refPic);
        refPic.setBounds(80, 140, 280, 370);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backgroundBlank.jpg"))); // NOI18N
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 450, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(refGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(refGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(refGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(refGuess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new refGuess().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TextArea;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JTextField guessTf;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel refPic;
    // End of variables declaration//GEN-END:variables
}
