/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

/**
 *
 * @author Richie Mangan
 * X13114514
 */
public class RulesRegsGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RulesRegsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        refBtn = new javax.swing.JButton();
        vanBtn = new javax.swing.JButton();
        gameBtn = new javax.swing.JButton();
        regBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Back Button (2).png"))); // NOI18N
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backHover.png"))); // NOI18N
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(390, 0, 60, 60);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2_2.png"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setFocusPainted(false);
        homeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2hover.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(0, 0, 60, 60);

        refBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/refsNew.png"))); // NOI18N
        refBtn.setBorderPainted(false);
        refBtn.setContentAreaFilled(false);
        refBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        refBtn.setDefaultCapable(false);
        refBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/refhover.png"))); // NOI18N
        refBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refBtnActionPerformed(evt);
            }
        });
        jPanel1.add(refBtn);
        refBtn.setBounds(140, 200, 310, 70);

        vanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/NewVanishClear.png"))); // NOI18N
        vanBtn.setBorderPainted(false);
        vanBtn.setContentAreaFilled(false);
        vanBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/NewVanish.png"))); // NOI18N
        vanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanBtnActionPerformed(evt);
            }
        });
        jPanel1.add(vanBtn);
        vanBtn.setBounds(245, 340, 210, 70);

        gameBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/goalWatch.png"))); // NOI18N
        gameBtn.setBorderPainted(false);
        gameBtn.setContentAreaFilled(false);
        gameBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/goalWatchHover.png"))); // NOI18N
        gameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameBtnActionPerformed(evt);
            }
        });
        jPanel1.add(gameBtn);
        gameBtn.setBounds(320, 480, 130, 80);

        regBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/ruleBook.png"))); // NOI18N
        regBtn.setBorderPainted(false);
        regBtn.setContentAreaFilled(false);
        regBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/rulebook hover.png"))); // NOI18N
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });
        jPanel1.add(regBtn);
        regBtn.setBounds(332, 613, 130, 100);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/BackgroundQuiz2.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-468)/2, (screenSize.height-745)/2, 468, 745);
    }// </editor-fold>//GEN-END:initComponents

    private void refBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refBtnActionPerformed
        // This button goes to the GUI for storing Referees
        RefereesGUI myReuse = new RefereesGUI();
        myReuse.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_refBtnActionPerformed

    private void vanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanBtnActionPerformed
        //This code runs the QuestionBankGUI that allows users to store questions for the Quiz
        QuestionBankGUI myGuess = new QuestionBankGUI();
        myGuess.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_vanBtnActionPerformed

    private void gameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameBtnActionPerformed
        //This code below runs the gameGUI, taking the questions from the above GUI
        GameGUI2 myGame = new GameGUI2();
        myGame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_gameBtnActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        //try and catch for linking to webpage with pdf of rule book. 
        try {
            //Set page url in this string. For eg, 
            String url = "http://www.fifa.com/mm/document/tournament/competition/fifa_wc_south_africa_2010_regulations_en_14123.pdf";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // This code allows the user to jump right back to the start of the app
        WorldCup myHome = new WorldCup();
        myHome.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // This code allows the user to go back 1 page at a time
        WorldCup home = new WorldCup();
        home.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RulesRegsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RulesRegsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RulesRegsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RulesRegsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new RulesRegsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton gameBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton refBtn;
    private javax.swing.JButton regBtn;
    private javax.swing.JButton vanBtn;
    // End of variables declaration//GEN-END:variables
}
