/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

/**
 *
 * @author x13451188
 */
public class stadium extends javax.swing.JFrame {

    /**
     * Creates new form stadium
     */
    public stadium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 700));
        getContentPane().setLayout(null);

        a.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium1.png"))); // NOI18N
        a.setBorderPainted(false);
        a.setContentAreaFilled(false);
        a.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium1o.png"))); // NOI18N
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(80, 210, 80, 60);

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium2.png"))); // NOI18N
        b.setBorderPainted(false);
        b.setContentAreaFilled(false);
        b.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium2o.png"))); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(220, 160, 80, 50);

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium3.png"))); // NOI18N
        c.setBorderPainted(false);
        c.setContentAreaFilled(false);
        c.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium3o.png"))); // NOI18N
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(320, 170, 70, 60);

        d.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium4.png"))); // NOI18N
        d.setBorderPainted(false);
        d.setContentAreaFilled(false);
        d.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium4o.png"))); // NOI18N
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(320, 230, 130, 90);

        e.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium5.png"))); // NOI18N
        e.setBorderPainted(false);
        e.setContentAreaFilled(false);
        e.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium5o.png"))); // NOI18N
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(330, 300, 100, 80);

        f.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium9.png"))); // NOI18N
        f.setBorderPainted(false);
        f.setContentAreaFilled(false);
        f.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium9o.png"))); // NOI18N
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(320, 380, 60, 60);

        g.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium10.png"))); // NOI18N
        g.setBorderPainted(false);
        g.setContentAreaFilled(false);
        g.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium10o.png"))); // NOI18N
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(280, 450, 60, 40);

        h.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium11.png"))); // NOI18N
        h.setBorderPainted(false);
        h.setContentAreaFilled(false);
        h.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium12o.png"))); // NOI18N
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(240, 490, 60, 50);

        i.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium8.png"))); // NOI18N
        i.setBorderPainted(false);
        i.setContentAreaFilled(false);
        i.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium8o.png"))); // NOI18N
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(220, 370, 90, 50);

        j.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium7.png"))); // NOI18N
        j.setBorderPainted(false);
        j.setContentAreaFilled(false);
        j.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium7o.png"))); // NOI18N
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });
        getContentPane().add(j);
        j.setBounds(130, 340, 80, 60);

        k.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium6.png"))); // NOI18N
        k.setBorderPainted(false);
        k.setContentAreaFilled(false);
        k.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium6o.png"))); // NOI18N
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });
        getContentPane().add(k);
        k.setBounds(220, 300, 80, 50);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2.png"))); // NOI18N
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/pinkroleover.png"))); // NOI18N
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home);
        home.setBounds(0, 0, 80, 70);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium99999.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/staddium99999o.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 540, 80, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/brazilnewmapo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 80, 470, 530);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backgroundnew.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 700);

        setSize(new java.awt.Dimension(465, 741));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        // TODO add your handling code here:
        stadiuminfo8 aS =new stadiuminfo8();
        aS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
         stadiuminfo11 bS =new stadiuminfo11();
        bS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
         stadiuminfo7 cS =new stadiuminfo7();
        cS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_cActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
           stadiuminfo5 dS =new stadiuminfo5();
        dS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_dActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
           stadiuminfo2 eS =new stadiuminfo2();
        eS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_eActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
           stadiuminfo fS =new stadiuminfo();
        fS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        // TODO add your handling code here:
           stadiuminfo3 gS =new stadiuminfo3();
        gS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        // TODO add your handling code here:
           stadiuminfo12 hS =new stadiuminfo12();
        hS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_hActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        // TODO add your handling code here:
           stadiuminfo4 iS =new stadiuminfo4();
        iS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_iActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        // TODO add your handling code here:
           stadiuminfo10 jS =new stadiuminfo10();
        jS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
        stadiuminfo9 kS =new stadiuminfo9();
        kS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_kActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        WorldCup myHome = new WorldCup();
        myHome.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_homeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         stadiuminfo6 lS =new stadiuminfo6();
        lS.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stadium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stadium().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton home;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton k;
    // End of variables declaration//GEN-END:variables

}