/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

import javax.swing.JOptionPane;


/**
 *
 *@author: Ian Cunnngham
 *@student Number: x13114425
 *@File: Teams.java
 */
public class Teams extends javax.swing.JFrame {
    /**
     * Creates new form Teams
     */
    
    public Teams() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        brazilBtn = new javax.swing.JButton();
        croatiaBtn = new javax.swing.JButton();
        cameroonBtn = new javax.swing.JButton();
        mexicoBtn = new javax.swing.JButton();
        spainBtn = new javax.swing.JButton();
        germanyBtn = new javax.swing.JButton();
        hollandBtn = new javax.swing.JButton();
        russiaBtn = new javax.swing.JButton();
        brazilLbl = new javax.swing.JLabel();
        spainLbl = new javax.swing.JLabel();
        englandBtn = new javax.swing.JButton();
        portugalBtn = new javax.swing.JButton();
        ghanaBtn = new javax.swing.JButton();
        iranBtn = new javax.swing.JButton();
        algeriaBtn = new javax.swing.JButton();
        koreaBtn = new javax.swing.JButton();
        japanBtn = new javax.swing.JButton();
        australiaBtn = new javax.swing.JButton();
        ivoryCoastBtn = new javax.swing.JButton();
        nigeriaBtn = new javax.swing.JButton();
        usaBtn = new javax.swing.JButton();
        costaRicaBtn = new javax.swing.JButton();
        hondurasBtn = new javax.swing.JButton();
        argentinaBtn = new javax.swing.JButton();
        chileBtn = new javax.swing.JButton();
        colombiaBtn = new javax.swing.JButton();
        ecuadorBtn = new javax.swing.JButton();
        uruguayBtn = new javax.swing.JButton();
        belgiumBtn = new javax.swing.JButton();
        bosniaBtn = new javax.swing.JButton();
        franceBtn = new javax.swing.JButton();
        greeceBtn = new javax.swing.JButton();
        italyBtn = new javax.swing.JButton();
        switzBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        englandLbl = new javax.swing.JLabel();
        australiaLbl = new javax.swing.JLabel();
        cameroonLbl = new javax.swing.JLabel();
        mexicoLbl = new javax.swing.JLabel();
        croatiaLbl = new javax.swing.JLabel();
        germanyLbl = new javax.swing.JLabel();
        hollandLbl = new javax.swing.JLabel();
        russiaLbl = new javax.swing.JLabel();
        portugalLbl = new javax.swing.JLabel();
        ghanaLbl = new javax.swing.JLabel();
        iranLbl = new javax.swing.JLabel();
        japanLbl = new javax.swing.JLabel();
        koreaLbl = new javax.swing.JLabel();
        algeriaLbl = new javax.swing.JLabel();
        ivoryCoastLbl = new javax.swing.JLabel();
        nigeriaLbl = new javax.swing.JLabel();
        usaLbl = new javax.swing.JLabel();
        costaRicaLbl = new javax.swing.JLabel();
        hondurasLbl = new javax.swing.JLabel();
        argentinaLbl = new javax.swing.JLabel();
        chileLbl = new javax.swing.JLabel();
        colombiaLbl = new javax.swing.JLabel();
        ecuadorLbl = new javax.swing.JLabel();
        uruguayLbl = new javax.swing.JLabel();
        belgiumLbl = new javax.swing.JLabel();
        bosniaLbl = new javax.swing.JLabel();
        franceLbl = new javax.swing.JLabel();
        greeceLbl = new javax.swing.JLabel();
        italyLbl = new javax.swing.JLabel();
        SwitzLbl = new javax.swing.JLabel();
        headingLbl = new javax.swing.JLabel();
        quizBtn = new javax.swing.JButton();
        dreamTeamBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 700));
        jPanel1.setLayout(null);

        brazilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Brazil.png"))); // NOI18N
        brazilBtn.setBorder(null);
        brazilBtn.setContentAreaFilled(false);
        brazilBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/brazilHover.fw.png"))); // NOI18N
        brazilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brazilBtnActionPerformed(evt);
            }
        });
        jPanel1.add(brazilBtn);
        brazilBtn.setBounds(60, 60, 58, 51);

        croatiaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Croatia.png"))); // NOI18N
        croatiaBtn.setBorder(null);
        croatiaBtn.setContentAreaFilled(false);
        croatiaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/croatiaHover.fw.png"))); // NOI18N
        croatiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croatiaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(croatiaBtn);
        croatiaBtn.setBounds(330, 60, 58, 51);

        cameroonBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Cameroon.png"))); // NOI18N
        cameroonBtn.setBorder(null);
        cameroonBtn.setContentAreaFilled(false);
        cameroonBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/cameroonHover.fw.png"))); // NOI18N
        cameroonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cameroonBtnActionPerformed(evt);
            }
        });
        jPanel1.add(cameroonBtn);
        cameroonBtn.setBounds(150, 60, 58, 51);

        mexicoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Mexico.png"))); // NOI18N
        mexicoBtn.setBorder(null);
        mexicoBtn.setContentAreaFilled(false);
        mexicoBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/mexicoHover.fw.png"))); // NOI18N
        mexicoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mexicoBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mexicoBtn);
        mexicoBtn.setBounds(240, 60, 58, 51);

        spainBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Spain.png"))); // NOI18N
        spainBtn.setBorder(null);
        spainBtn.setContentAreaFilled(false);
        spainBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/spainHover.fw.png"))); // NOI18N
        spainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spainBtnActionPerformed(evt);
            }
        });
        jPanel1.add(spainBtn);
        spainBtn.setBounds(60, 140, 58, 51);

        germanyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Germany.png"))); // NOI18N
        germanyBtn.setBorder(null);
        germanyBtn.setContentAreaFilled(false);
        germanyBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/germanyHover.fw.png"))); // NOI18N
        germanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(germanyBtn);
        germanyBtn.setBounds(150, 140, 58, 51);

        hollandBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Holland.png"))); // NOI18N
        hollandBtn.setBorder(null);
        hollandBtn.setContentAreaFilled(false);
        hollandBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/hollandHover.fw.png"))); // NOI18N
        hollandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hollandBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hollandBtn);
        hollandBtn.setBounds(240, 140, 58, 51);

        russiaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Russia.png"))); // NOI18N
        russiaBtn.setBorder(null);
        russiaBtn.setContentAreaFilled(false);
        russiaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/russiaHover.fw.png"))); // NOI18N
        russiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                russiaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(russiaBtn);
        russiaBtn.setBounds(330, 140, 58, 51);

        brazilLbl.setBackground(new java.awt.Color(204, 204, 204));
        brazilLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        brazilLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brazilLbl.setText("Brazil");
        brazilLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        brazilLbl.setOpaque(true);
        jPanel1.add(brazilLbl);
        brazilLbl.setBounds(65, 115, 50, 23);

        spainLbl.setBackground(new java.awt.Color(204, 204, 204));
        spainLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        spainLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spainLbl.setText("Spain");
        spainLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spainLbl.setOpaque(true);
        jPanel1.add(spainLbl);
        spainLbl.setBounds(65, 195, 50, 23);

        englandBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/England.png"))); // NOI18N
        englandBtn.setBorder(null);
        englandBtn.setContentAreaFilled(false);
        englandBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/englandHover.fw.png"))); // NOI18N
        englandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englandBtnActionPerformed(evt);
            }
        });
        jPanel1.add(englandBtn);
        englandBtn.setBounds(60, 220, 58, 51);

        portugalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Portugal.png"))); // NOI18N
        portugalBtn.setBorder(null);
        portugalBtn.setContentAreaFilled(false);
        portugalBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/portugalHover.fw.png"))); // NOI18N
        portugalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portugalBtnActionPerformed(evt);
            }
        });
        jPanel1.add(portugalBtn);
        portugalBtn.setBounds(150, 220, 58, 51);

        ghanaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Ghana.png"))); // NOI18N
        ghanaBtn.setBorder(null);
        ghanaBtn.setContentAreaFilled(false);
        ghanaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/ghanaHover.fw.png"))); // NOI18N
        ghanaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghanaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ghanaBtn);
        ghanaBtn.setBounds(240, 220, 58, 51);

        iranBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Iran.png"))); // NOI18N
        iranBtn.setBorder(null);
        iranBtn.setContentAreaFilled(false);
        iranBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/iranHover.fw.png"))); // NOI18N
        iranBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iranBtnActionPerformed(evt);
            }
        });
        jPanel1.add(iranBtn);
        iranBtn.setBounds(330, 220, 58, 51);

        algeriaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Algeria.png"))); // NOI18N
        algeriaBtn.setBorder(null);
        algeriaBtn.setContentAreaFilled(false);
        algeriaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/algeriaHover.fw.png"))); // NOI18N
        algeriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algeriaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(algeriaBtn);
        algeriaBtn.setBounds(330, 300, 58, 51);

        koreaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Korea.png"))); // NOI18N
        koreaBtn.setBorder(null);
        koreaBtn.setContentAreaFilled(false);
        koreaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/koreaHover.fw.png"))); // NOI18N
        koreaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koreaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(koreaBtn);
        koreaBtn.setBounds(240, 300, 58, 51);

        japanBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Japan.png"))); // NOI18N
        japanBtn.setBorder(null);
        japanBtn.setContentAreaFilled(false);
        japanBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/japanHover.fw.png"))); // NOI18N
        japanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japanBtnActionPerformed(evt);
            }
        });
        jPanel1.add(japanBtn);
        japanBtn.setBounds(150, 300, 58, 51);

        australiaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Australia.png"))); // NOI18N
        australiaBtn.setBorder(null);
        australiaBtn.setContentAreaFilled(false);
        australiaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/australiaHover.fw.png"))); // NOI18N
        australiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                australiaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(australiaBtn);
        australiaBtn.setBounds(60, 300, 58, 51);

        ivoryCoastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Ivory Coast.png"))); // NOI18N
        ivoryCoastBtn.setBorder(null);
        ivoryCoastBtn.setContentAreaFilled(false);
        ivoryCoastBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/ivoryCoastHover.fw.png"))); // NOI18N
        ivoryCoastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ivoryCoastBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ivoryCoastBtn);
        ivoryCoastBtn.setBounds(60, 380, 58, 51);

        nigeriaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Nigeria.png"))); // NOI18N
        nigeriaBtn.setBorder(null);
        nigeriaBtn.setContentAreaFilled(false);
        nigeriaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/nigeriaHover.fw.png"))); // NOI18N
        nigeriaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nigeriaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nigeriaBtn);
        nigeriaBtn.setBounds(150, 380, 58, 51);

        usaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/USA.png"))); // NOI18N
        usaBtn.setBorder(null);
        usaBtn.setContentAreaFilled(false);
        usaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/usaHover.fw.png"))); // NOI18N
        usaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(usaBtn);
        usaBtn.setBounds(240, 380, 58, 51);

        costaRicaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Costa-Rica.png"))); // NOI18N
        costaRicaBtn.setBorder(null);
        costaRicaBtn.setContentAreaFilled(false);
        costaRicaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/costaRicaHover.fw.png"))); // NOI18N
        costaRicaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costaRicaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(costaRicaBtn);
        costaRicaBtn.setBounds(330, 380, 58, 51);

        hondurasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Honduras.png"))); // NOI18N
        hondurasBtn.setBorder(null);
        hondurasBtn.setContentAreaFilled(false);
        hondurasBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/hondurasHover.fw.png"))); // NOI18N
        hondurasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hondurasBtnActionPerformed(evt);
            }
        });
        jPanel1.add(hondurasBtn);
        hondurasBtn.setBounds(60, 460, 58, 51);

        argentinaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Argentina.png"))); // NOI18N
        argentinaBtn.setBorder(null);
        argentinaBtn.setContentAreaFilled(false);
        argentinaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/argentinaHover.fw.png"))); // NOI18N
        argentinaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                argentinaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(argentinaBtn);
        argentinaBtn.setBounds(150, 460, 58, 51);

        chileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Chile.png"))); // NOI18N
        chileBtn.setBorder(null);
        chileBtn.setContentAreaFilled(false);
        chileBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/chileHover.fw.png"))); // NOI18N
        chileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chileBtnActionPerformed(evt);
            }
        });
        jPanel1.add(chileBtn);
        chileBtn.setBounds(240, 460, 58, 51);

        colombiaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Colombia.png"))); // NOI18N
        colombiaBtn.setBorder(null);
        colombiaBtn.setContentAreaFilled(false);
        colombiaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/colombiaHover.fw.png"))); // NOI18N
        colombiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colombiaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(colombiaBtn);
        colombiaBtn.setBounds(330, 460, 58, 51);

        ecuadorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Ecuador.png"))); // NOI18N
        ecuadorBtn.setBorder(null);
        ecuadorBtn.setContentAreaFilled(false);
        ecuadorBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/ecuadorHover.fw.png"))); // NOI18N
        ecuadorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecuadorBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ecuadorBtn);
        ecuadorBtn.setBounds(60, 540, 58, 51);

        uruguayBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Uruguay.png"))); // NOI18N
        uruguayBtn.setBorder(null);
        uruguayBtn.setContentAreaFilled(false);
        uruguayBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/uruguayHover.fw.png"))); // NOI18N
        uruguayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uruguayBtnActionPerformed(evt);
            }
        });
        jPanel1.add(uruguayBtn);
        uruguayBtn.setBounds(150, 540, 58, 51);

        belgiumBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Belgium.png"))); // NOI18N
        belgiumBtn.setBorder(null);
        belgiumBtn.setContentAreaFilled(false);
        belgiumBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/belgiumHover.fw.png"))); // NOI18N
        belgiumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belgiumBtnActionPerformed(evt);
            }
        });
        jPanel1.add(belgiumBtn);
        belgiumBtn.setBounds(240, 540, 58, 51);

        bosniaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Bosnia.png"))); // NOI18N
        bosniaBtn.setBorder(null);
        bosniaBtn.setContentAreaFilled(false);
        bosniaBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/bosniaHover.fw.png"))); // NOI18N
        bosniaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bosniaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(bosniaBtn);
        bosniaBtn.setBounds(330, 540, 58, 51);

        franceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/France.png"))); // NOI18N
        franceBtn.setBorder(null);
        franceBtn.setContentAreaFilled(false);
        franceBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/franceHover.fw.png"))); // NOI18N
        franceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                franceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(franceBtn);
        franceBtn.setBounds(60, 620, 58, 51);

        greeceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Greece.png"))); // NOI18N
        greeceBtn.setBorder(null);
        greeceBtn.setContentAreaFilled(false);
        greeceBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/greeceHover.fw.png"))); // NOI18N
        greeceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greeceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(greeceBtn);
        greeceBtn.setBounds(150, 620, 58, 51);

        italyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Italy.png"))); // NOI18N
        italyBtn.setBorder(null);
        italyBtn.setContentAreaFilled(false);
        italyBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/italyHover.fw.png"))); // NOI18N
        italyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(italyBtn);
        italyBtn.setBounds(240, 620, 58, 51);

        switzBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Switzerland.png"))); // NOI18N
        switzBtn.setBorder(null);
        switzBtn.setContentAreaFilled(false);
        switzBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/switzHover.fw.png"))); // NOI18N
        switzBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switzBtnActionPerformed(evt);
            }
        });
        jPanel1.add(switzBtn);
        switzBtn.setBounds(330, 620, 58, 51);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeButton2.png"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/homeHover.fw.png"))); // NOI18N
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel1.add(homeBtn);
        homeBtn.setBounds(5, 5, 50, 50);

        englandLbl.setBackground(new java.awt.Color(204, 204, 204));
        englandLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        englandLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        englandLbl.setText("England");
        englandLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        englandLbl.setOpaque(true);
        jPanel1.add(englandLbl);
        englandLbl.setBounds(60, 275, 60, 23);

        australiaLbl.setBackground(new java.awt.Color(204, 204, 204));
        australiaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        australiaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        australiaLbl.setText("Australia");
        australiaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        australiaLbl.setOpaque(true);
        jPanel1.add(australiaLbl);
        australiaLbl.setBounds(55, 355, 70, 23);

        cameroonLbl.setBackground(new java.awt.Color(204, 204, 204));
        cameroonLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        cameroonLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cameroonLbl.setText("Cameroon");
        cameroonLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cameroonLbl.setOpaque(true);
        jPanel1.add(cameroonLbl);
        cameroonLbl.setBounds(145, 115, 70, 23);

        mexicoLbl.setBackground(new java.awt.Color(204, 204, 204));
        mexicoLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        mexicoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mexicoLbl.setText("Mexico");
        mexicoLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mexicoLbl.setOpaque(true);
        jPanel1.add(mexicoLbl);
        mexicoLbl.setBounds(245, 115, 50, 23);

        croatiaLbl.setBackground(new java.awt.Color(204, 204, 204));
        croatiaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        croatiaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        croatiaLbl.setText("Croatia");
        croatiaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        croatiaLbl.setOpaque(true);
        jPanel1.add(croatiaLbl);
        croatiaLbl.setBounds(330, 115, 60, 23);

        germanyLbl.setBackground(new java.awt.Color(204, 204, 204));
        germanyLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        germanyLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        germanyLbl.setText("Germany");
        germanyLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        germanyLbl.setOpaque(true);
        jPanel1.add(germanyLbl);
        germanyLbl.setBounds(150, 195, 60, 23);

        hollandLbl.setBackground(new java.awt.Color(204, 204, 204));
        hollandLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        hollandLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hollandLbl.setText("Holland");
        hollandLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hollandLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hollandLbl.setOpaque(true);
        jPanel1.add(hollandLbl);
        hollandLbl.setBounds(240, 195, 60, 23);

        russiaLbl.setBackground(new java.awt.Color(204, 204, 204));
        russiaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        russiaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        russiaLbl.setText("Russia");
        russiaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        russiaLbl.setOpaque(true);
        jPanel1.add(russiaLbl);
        russiaLbl.setBounds(335, 195, 50, 23);

        portugalLbl.setBackground(new java.awt.Color(204, 204, 204));
        portugalLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        portugalLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        portugalLbl.setText("Portugal");
        portugalLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        portugalLbl.setOpaque(true);
        jPanel1.add(portugalLbl);
        portugalLbl.setBounds(150, 275, 60, 23);

        ghanaLbl.setBackground(new java.awt.Color(204, 204, 204));
        ghanaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        ghanaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ghanaLbl.setText("Ghana");
        ghanaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ghanaLbl.setOpaque(true);
        jPanel1.add(ghanaLbl);
        ghanaLbl.setBounds(245, 275, 50, 23);

        iranLbl.setBackground(new java.awt.Color(204, 204, 204));
        iranLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        iranLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iranLbl.setText("Iran");
        iranLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iranLbl.setOpaque(true);
        jPanel1.add(iranLbl);
        iranLbl.setBounds(340, 275, 40, 23);

        japanLbl.setBackground(new java.awt.Color(204, 204, 204));
        japanLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        japanLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        japanLbl.setText("Japan");
        japanLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        japanLbl.setOpaque(true);
        jPanel1.add(japanLbl);
        japanLbl.setBounds(160, 355, 40, 23);

        koreaLbl.setBackground(new java.awt.Color(204, 204, 204));
        koreaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        koreaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        koreaLbl.setText("South Korea");
        koreaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        koreaLbl.setOpaque(true);
        jPanel1.add(koreaLbl);
        koreaLbl.setBounds(225, 355, 90, 23);

        algeriaLbl.setBackground(new java.awt.Color(204, 204, 204));
        algeriaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        algeriaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        algeriaLbl.setText("Algeria");
        algeriaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        algeriaLbl.setOpaque(true);
        jPanel1.add(algeriaLbl);
        algeriaLbl.setBounds(330, 355, 60, 23);

        ivoryCoastLbl.setBackground(new java.awt.Color(204, 204, 204));
        ivoryCoastLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        ivoryCoastLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ivoryCoastLbl.setText("Ivory Coast");
        ivoryCoastLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ivoryCoastLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ivoryCoastLbl.setOpaque(true);
        jPanel1.add(ivoryCoastLbl);
        ivoryCoastLbl.setBounds(50, 435, 80, 23);

        nigeriaLbl.setBackground(new java.awt.Color(204, 204, 204));
        nigeriaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        nigeriaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nigeriaLbl.setText("Nigeria");
        nigeriaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nigeriaLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nigeriaLbl.setOpaque(true);
        jPanel1.add(nigeriaLbl);
        nigeriaLbl.setBounds(150, 435, 60, 23);

        usaLbl.setBackground(new java.awt.Color(204, 204, 204));
        usaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        usaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usaLbl.setText("USA");
        usaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usaLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        usaLbl.setOpaque(true);
        jPanel1.add(usaLbl);
        usaLbl.setBounds(255, 435, 30, 23);

        costaRicaLbl.setBackground(new java.awt.Color(204, 204, 204));
        costaRicaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        costaRicaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costaRicaLbl.setText("Costa-Rica");
        costaRicaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        costaRicaLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        costaRicaLbl.setOpaque(true);
        jPanel1.add(costaRicaLbl);
        costaRicaLbl.setBounds(320, 435, 80, 23);

        hondurasLbl.setBackground(new java.awt.Color(204, 204, 204));
        hondurasLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        hondurasLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hondurasLbl.setText("Honduras");
        hondurasLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hondurasLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hondurasLbl.setOpaque(true);
        jPanel1.add(hondurasLbl);
        hondurasLbl.setBounds(60, 515, 60, 23);

        argentinaLbl.setBackground(new java.awt.Color(204, 204, 204));
        argentinaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        argentinaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        argentinaLbl.setText("Argentina");
        argentinaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        argentinaLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        argentinaLbl.setOpaque(true);
        jPanel1.add(argentinaLbl);
        argentinaLbl.setBounds(145, 515, 70, 23);

        chileLbl.setBackground(new java.awt.Color(204, 204, 204));
        chileLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        chileLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chileLbl.setText("Chile");
        chileLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chileLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        chileLbl.setOpaque(true);
        jPanel1.add(chileLbl);
        chileLbl.setBounds(250, 515, 40, 23);

        colombiaLbl.setBackground(new java.awt.Color(204, 204, 204));
        colombiaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        colombiaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colombiaLbl.setText("Colombia");
        colombiaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        colombiaLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colombiaLbl.setOpaque(true);
        jPanel1.add(colombiaLbl);
        colombiaLbl.setBounds(333, 515, 56, 23);

        ecuadorLbl.setBackground(new java.awt.Color(204, 204, 204));
        ecuadorLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        ecuadorLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ecuadorLbl.setText("Ecuador");
        ecuadorLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ecuadorLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ecuadorLbl.setOpaque(true);
        jPanel1.add(ecuadorLbl);
        ecuadorLbl.setBounds(60, 596, 60, 23);

        uruguayLbl.setBackground(new java.awt.Color(204, 204, 204));
        uruguayLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        uruguayLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        uruguayLbl.setText("Uruguay");
        uruguayLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uruguayLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        uruguayLbl.setOpaque(true);
        jPanel1.add(uruguayLbl);
        uruguayLbl.setBounds(150, 596, 60, 23);

        belgiumLbl.setBackground(new java.awt.Color(204, 204, 204));
        belgiumLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        belgiumLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        belgiumLbl.setText("Belgium");
        belgiumLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        belgiumLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        belgiumLbl.setOpaque(true);
        jPanel1.add(belgiumLbl);
        belgiumLbl.setBounds(245, 596, 49, 23);

        bosniaLbl.setBackground(new java.awt.Color(204, 204, 204));
        bosniaLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        bosniaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bosniaLbl.setText("Bosnia");
        bosniaLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bosniaLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bosniaLbl.setOpaque(true);
        jPanel1.add(bosniaLbl);
        bosniaLbl.setBounds(340, 596, 42, 23);

        franceLbl.setBackground(new java.awt.Color(204, 204, 204));
        franceLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        franceLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        franceLbl.setText("France");
        franceLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        franceLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        franceLbl.setOpaque(true);
        jPanel1.add(franceLbl);
        franceLbl.setBounds(65, 675, 50, 23);

        greeceLbl.setBackground(new java.awt.Color(204, 204, 204));
        greeceLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        greeceLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greeceLbl.setText("Greece");
        greeceLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        greeceLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        greeceLbl.setOpaque(true);
        jPanel1.add(greeceLbl);
        greeceLbl.setBounds(155, 675, 50, 23);

        italyLbl.setBackground(new java.awt.Color(204, 204, 204));
        italyLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        italyLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        italyLbl.setText("Italy");
        italyLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        italyLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        italyLbl.setOpaque(true);
        jPanel1.add(italyLbl);
        italyLbl.setBounds(250, 675, 40, 23);

        SwitzLbl.setBackground(new java.awt.Color(204, 204, 204));
        SwitzLbl.setFont(new java.awt.Font("Mangal", 1, 11)); // NOI18N
        SwitzLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SwitzLbl.setText("Switzerland");
        SwitzLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SwitzLbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SwitzLbl.setOpaque(true);
        jPanel1.add(SwitzLbl);
        SwitzLbl.setBounds(320, 675, 80, 23);

        headingLbl.setFont(new java.awt.Font("DotumChe", 1, 30)); // NOI18N
        headingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Teams.fw.png"))); // NOI18N
        jPanel1.add(headingLbl);
        headingLbl.setBounds(120, 10, 200, 40);

        quizBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Quiz.fw.png"))); // NOI18N
        quizBtn.setBorder(null);
        quizBtn.setContentAreaFilled(false);
        quizBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        quizBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/quizHover.fw.png"))); // NOI18N
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });
        jPanel1.add(quizBtn);
        quizBtn.setBounds(335, 5, 50, 50);

        dreamTeamBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/football.fw.png"))); // NOI18N
        dreamTeamBtn.setBorder(null);
        dreamTeamBtn.setContentAreaFilled(false);
        dreamTeamBtn.setPreferredSize(new java.awt.Dimension(55, 55));
        dreamTeamBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/footballHover.fw.png"))); // NOI18N
        dreamTeamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dreamTeamBtnActionPerformed(evt);
            }
        });
        jPanel1.add(dreamTeamBtn);
        dreamTeamBtn.setBounds(395, 5, 55, 55);

        backgroundLbl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backgroundClear.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void mexicoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mexicoBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo = new TeamsInfo();
        tInfo.setVisible(true);
        tInfo.mexico();
       
        this.dispose();
    }//GEN-LAST:event_mexicoBtnActionPerformed

    private void brazilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brazilBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo2 = new TeamsInfo();
        tInfo2.setVisible(true);
        tInfo2.brazil();
        
        this.dispose();
    }//GEN-LAST:event_brazilBtnActionPerformed

    private void iranBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iranBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo3 = new TeamsInfo();
        tInfo3.setVisible(true);
        tInfo3.iran();
        
        this.dispose();
    }//GEN-LAST:event_iranBtnActionPerformed

    private void hondurasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hondurasBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo4 = new TeamsInfo();
        tInfo4.setVisible(true);
        tInfo4.honduras();
        
        this.dispose();
    }//GEN-LAST:event_hondurasBtnActionPerformed

    private void croatiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croatiaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo5 = new TeamsInfo();
        tInfo5.setVisible(true);
        tInfo5.croatia();
        
        this.dispose();
    }//GEN-LAST:event_croatiaBtnActionPerformed

    private void germanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanyBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo6 = new TeamsInfo();
        tInfo6.setVisible(true); 
        tInfo6.germany();
        
        this.dispose();
    }//GEN-LAST:event_germanyBtnActionPerformed

    private void greeceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greeceBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo7 = new TeamsInfo();
        tInfo7.setVisible(true);
        tInfo7.greece();
        
        this.dispose();
    }//GEN-LAST:event_greeceBtnActionPerformed

    private void franceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_franceBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo8 = new TeamsInfo();
        tInfo8.setVisible(true);
        tInfo8.france();
        
        this.dispose();
    }//GEN-LAST:event_franceBtnActionPerformed

    private void cameroonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cameroonBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo9 = new TeamsInfo();
        tInfo9.setVisible(true);
        tInfo9.cameroon();
        
        this.dispose();
    }//GEN-LAST:event_cameroonBtnActionPerformed

    private void uruguayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uruguayBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo10 = new TeamsInfo();
        tInfo10.setVisible(true);
        tInfo10.uruguay();
        
        this.dispose();
    }//GEN-LAST:event_uruguayBtnActionPerformed

    private void ecuadorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecuadorBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo11 = new TeamsInfo();
        tInfo11.setVisible(true);
        tInfo11.ecuador();
        
        this.dispose();
    }//GEN-LAST:event_ecuadorBtnActionPerformed

    private void belgiumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belgiumBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo12 = new TeamsInfo();
        tInfo12.setVisible(true);
        tInfo12.belgium();
        
        this.dispose();
    }//GEN-LAST:event_belgiumBtnActionPerformed

    private void argentinaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_argentinaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo13 = new TeamsInfo();
        tInfo13.setVisible(true);
        tInfo13.argentina();
        
        this.dispose();
    }//GEN-LAST:event_argentinaBtnActionPerformed

    private void chileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chileBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo14 = new TeamsInfo();
        tInfo14.setVisible(true);
        tInfo14.chile();
        
        this.dispose();
    }//GEN-LAST:event_chileBtnActionPerformed

    private void colombiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colombiaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo15 = new TeamsInfo();
        tInfo15.setVisible(true);
        tInfo15.colombia();
        
        this.dispose();
    }//GEN-LAST:event_colombiaBtnActionPerformed

    private void italyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italyBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo16 = new TeamsInfo();
        tInfo16.setVisible(true);
        tInfo16.italy();
        
        this.dispose();
    }//GEN-LAST:event_italyBtnActionPerformed

    private void switzBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switzBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo17 = new TeamsInfo();
        tInfo17.setVisible(true);
        tInfo17.switzerland();
        
        this.dispose();
    }//GEN-LAST:event_switzBtnActionPerformed

    private void ivoryCoastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ivoryCoastBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo18 = new TeamsInfo();
        tInfo18.setVisible(true);
        tInfo18.ivoryCoast();
        
        this.dispose();
    }//GEN-LAST:event_ivoryCoastBtnActionPerformed

    private void nigeriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nigeriaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo19 = new TeamsInfo();
        tInfo19.setVisible(true);
        tInfo19.nigeria();
        
        this.dispose();
    }//GEN-LAST:event_nigeriaBtnActionPerformed

    private void usaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo20 = new TeamsInfo();
        tInfo20.setVisible(true);
        tInfo20.usa();
        
        this.dispose();
    }//GEN-LAST:event_usaBtnActionPerformed

    private void costaRicaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costaRicaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo21 = new TeamsInfo();
        tInfo21.setVisible(true);
        tInfo21.costaRica();
        
        this.dispose();
    }//GEN-LAST:event_costaRicaBtnActionPerformed

    private void australiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_australiaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo22 = new TeamsInfo();
        tInfo22.setVisible(true);
        tInfo22.australia();
        
        this.dispose();
    }//GEN-LAST:event_australiaBtnActionPerformed

    private void japanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japanBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo23 = new TeamsInfo();
        tInfo23.setVisible(true);
        tInfo23.japan();
        
        this.dispose();
    }//GEN-LAST:event_japanBtnActionPerformed

    private void koreaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koreaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo24 = new TeamsInfo();
        tInfo24.setVisible(true);
        tInfo24.korea();
        
        this.dispose();
    }//GEN-LAST:event_koreaBtnActionPerformed

    private void algeriaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algeriaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo25 = new TeamsInfo();
        tInfo25.setVisible(true);
        tInfo25.algeria();
        
        this.dispose();
    }//GEN-LAST:event_algeriaBtnActionPerformed

    private void englandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englandBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo26 = new TeamsInfo();
        tInfo26.setVisible(true);
        tInfo26.england();
        
        this.dispose();
    }//GEN-LAST:event_englandBtnActionPerformed

    private void portugalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portugalBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo27 = new TeamsInfo();
        tInfo27.setVisible(true);
        tInfo27.portugal();
        
        this.dispose();
    }//GEN-LAST:event_portugalBtnActionPerformed

    private void ghanaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghanaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo28 = new TeamsInfo();
        tInfo28.setVisible(true);
        tInfo28.ghana();
        
        this.dispose();
    }//GEN-LAST:event_ghanaBtnActionPerformed

    private void spainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spainBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo29 = new TeamsInfo();
        tInfo29.setVisible(true);
        tInfo29.spain();
        
        this.dispose();
    }//GEN-LAST:event_spainBtnActionPerformed

    private void hollandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hollandBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo30 = new TeamsInfo();
        tInfo30.setVisible(true);
        tInfo30.holland();
        
        this.dispose();
    }//GEN-LAST:event_hollandBtnActionPerformed

    private void russiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_russiaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo31 = new TeamsInfo();
        tInfo31.setVisible(true);
        tInfo31.russia();
        
        this.dispose();
    }//GEN-LAST:event_russiaBtnActionPerformed

    private void bosniaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bosniaBtnActionPerformed
        // TODO add your handling code here:
        TeamsInfo tInfo32 = new TeamsInfo();
        tInfo32.setVisible(true);
        tInfo32.bosnia();
        
        this.dispose();
    }//GEN-LAST:event_bosniaBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        WorldCup home = new WorldCup();
        home.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        //opens the quiz GUI
        Quiz myQuiz = new Quiz();
        myQuiz.setVisible(true);
        
        this.dispose();     //closes the current GUI that is open
    }//GEN-LAST:event_quizBtnActionPerformed

    private void dreamTeamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dreamTeamBtnActionPerformed
        // TODO add your handling code here:
        DreamTeamGUI d = new DreamTeamGUI();
        d.setVisible(true);
        JOptionPane.showMessageDialog(null, "Please enter the Dream Team of your choice and the name of your team");
           
        this.dispose();
    }//GEN-LAST:event_dreamTeamBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teams().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SwitzLbl;
    private javax.swing.JButton algeriaBtn;
    private javax.swing.JLabel algeriaLbl;
    private javax.swing.JButton argentinaBtn;
    private javax.swing.JLabel argentinaLbl;
    private javax.swing.JButton australiaBtn;
    private javax.swing.JLabel australiaLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton belgiumBtn;
    private javax.swing.JLabel belgiumLbl;
    private javax.swing.JButton bosniaBtn;
    private javax.swing.JLabel bosniaLbl;
    private javax.swing.JButton brazilBtn;
    private javax.swing.JLabel brazilLbl;
    private javax.swing.JButton cameroonBtn;
    private javax.swing.JLabel cameroonLbl;
    private javax.swing.JButton chileBtn;
    private javax.swing.JLabel chileLbl;
    private javax.swing.JButton colombiaBtn;
    private javax.swing.JLabel colombiaLbl;
    private javax.swing.JButton costaRicaBtn;
    private javax.swing.JLabel costaRicaLbl;
    private javax.swing.JButton croatiaBtn;
    private javax.swing.JLabel croatiaLbl;
    private javax.swing.JButton dreamTeamBtn;
    private javax.swing.JButton ecuadorBtn;
    private javax.swing.JLabel ecuadorLbl;
    private javax.swing.JButton englandBtn;
    private javax.swing.JLabel englandLbl;
    private javax.swing.JButton franceBtn;
    private javax.swing.JLabel franceLbl;
    private javax.swing.JButton germanyBtn;
    private javax.swing.JLabel germanyLbl;
    private javax.swing.JButton ghanaBtn;
    private javax.swing.JLabel ghanaLbl;
    private javax.swing.JButton greeceBtn;
    private javax.swing.JLabel greeceLbl;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JButton hollandBtn;
    private javax.swing.JLabel hollandLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton hondurasBtn;
    private javax.swing.JLabel hondurasLbl;
    private javax.swing.JButton iranBtn;
    private javax.swing.JLabel iranLbl;
    private javax.swing.JButton italyBtn;
    private javax.swing.JLabel italyLbl;
    private javax.swing.JButton ivoryCoastBtn;
    private javax.swing.JLabel ivoryCoastLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton japanBtn;
    private javax.swing.JLabel japanLbl;
    private javax.swing.JButton koreaBtn;
    private javax.swing.JLabel koreaLbl;
    private javax.swing.JButton mexicoBtn;
    private javax.swing.JLabel mexicoLbl;
    private javax.swing.JButton nigeriaBtn;
    private javax.swing.JLabel nigeriaLbl;
    private javax.swing.JButton portugalBtn;
    private javax.swing.JLabel portugalLbl;
    private javax.swing.JButton quizBtn;
    private javax.swing.JButton russiaBtn;
    private javax.swing.JLabel russiaLbl;
    private javax.swing.JButton spainBtn;
    private javax.swing.JLabel spainLbl;
    private javax.swing.JButton switzBtn;
    private javax.swing.JButton uruguayBtn;
    private javax.swing.JLabel uruguayLbl;
    private javax.swing.JButton usaBtn;
    private javax.swing.JLabel usaLbl;
    // End of variables declaration//GEN-END:variables
}
