/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package teams;

/**
 *
 * @author Ian C
 */
public class WorldCup extends javax.swing.JFrame {

    /**
     * Creates new form WorldCup
     */
    public WorldCup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        groupsBtn = new javax.swing.JButton();
        venuesBtn = new javax.swing.JButton();
        rulesBtn = new javax.swing.JButton();
        teamsBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        groupsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/groups.png"))); // NOI18N
        groupsBtn.setBorder(null);
        groupsBtn.setContentAreaFilled(false);
        groupsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/groups hover.png"))); // NOI18N
        groupsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(groupsBtn);
        groupsBtn.setBounds(190, 20, 250, 350);

        venuesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium.png"))); // NOI18N
        venuesBtn.setBorder(null);
        venuesBtn.setContentAreaFilled(false);
        venuesBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/stadium hover.png"))); // NOI18N
        venuesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venuesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(venuesBtn);
        venuesBtn.setBounds(89, 350, 360, 180);

        rulesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/ref.png"))); // NOI18N
        rulesBtn.setBorder(null);
        rulesBtn.setContentAreaFilled(false);
        rulesBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/Ref hover.png"))); // NOI18N
        rulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rulesBtn);
        rulesBtn.setBounds(0, 230, 230, 470);

        teamsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/teams.png"))); // NOI18N
        teamsBtn.setBorder(null);
        teamsBtn.setContentAreaFilled(false);
        teamsBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/teams hover.png"))); // NOI18N
        teamsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamsBtnActionPerformed(evt);
            }
        });
        jPanel1.add(teamsBtn);
        teamsBtn.setBounds(190, 460, 250, 210);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teams/pictures/backgroundClear.jpg"))); // NOI18N
        jPanel1.add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 450, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void teamsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamsBtnActionPerformed
        // TODO add your handling code here:
        Teams myTeams = new Teams();
        myTeams.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_teamsBtnActionPerformed

    private void groupsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsBtnActionPerformed
        GroupsGUI myGroups = new GroupsGUI();
        myGroups.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_groupsBtnActionPerformed

    private void venuesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venuesBtnActionPerformed
        stadium myVenues = new stadium();
        myVenues.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_venuesBtnActionPerformed

    private void rulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBtnActionPerformed
        RulesRegsGUI myRules = new RulesRegsGUI();
        myRules.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_rulesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorldCup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorldCup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorldCup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorldCup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WorldCup().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton groupsBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton rulesBtn;
    private javax.swing.JButton teamsBtn;
    private javax.swing.JButton venuesBtn;
    // End of variables declaration//GEN-END:variables
}
